In [39]:
import pandas as pd
import numpy as np
from collections import Counter
pd.options.display.max_rows=100

In [40]:
prateek_df = pd.read_csv("/home/prateekagarw_umass_edu/p_file/Prateek Annotations.csv", skipinitialspace=True).replace(np.nan, '')
deep_df = pd.read_csv("/home/prateekagarw_umass_edu/p_file/Deep Annotations.csv", skipinitialspace=True).replace(np.nan, '')
kartik_df = pd.read_csv("/home/prateekagarw_umass_edu/p_file/Kartik Annotations.csv", skipinitialspace=True).replace(np.nan, '')
lakshita_df = pd.read_csv("/home/prateekagarw_umass_edu/p_file/Lakshita Annotations.csv", skipinitialspace=True).replace(np.nan, '')

In [41]:
#Calculate Top-1 Agreement
agreement = 0
for values in zip(prateek_df['adjective_1'].tolist(),lakshita_df['adjective_1'].to_list(),deep_df['adjective_1'].tolist(),kartik_df['adjective_1'].tolist()):
    if (values[0] == values[1] == values[2] == values[3]):
        agreement+=1
    else:
        continue

print(agreement)
print(agreement/257)

117
0.45525291828793774

In [42]:
#Locate the Negatives and add them to the all_aug_dataset
negative_adjectives = []

for values in zip(prateek_df['negative_adj'].tolist(),lakshita_df['negative_adj'].to_list(),deep_df['negative_adj'].tolist(),kartik_df['negative_adj'].tolist()):
    #Create the negative set
    negative_set = set({values[0],values[1],values[2],values[3]})
    if '' in negative_set:
        negative_set.remove('')
    negative_adjectives.append(list(negative_set))
    
# print(negative_adjectives)

In [43]:
all_labels_aug = pd.read_csv("/home/prateekagarw_umass_edu/p_file/all_labels_aug.csv", skipinitialspace=True)
all_labels_aug['image_name'] = all_labels_aug['image_name'] + ".jpg"
all_labels_aug['negative_adj'] = negative_adjectives
all_labels_aug['object_1'] = prateek_df['object_1']
all_labels_aug['object_2'] = prateek_df['object_2']
all_labels_aug

,image_name,adjective_1,adjective_2,negative_adj,object_1,object_2
0,p_0.jpg,bigger,smaller,"[bluer, hairier]",dogs,
1,p_1.jpg,cleaner,dirtier,[bigger],hands,
2,p_2.jpg,hairier,balder,"[longer, thicker]",cats,
3,p_3.jpg,younger,older,"[denser, cleaner]",persons,
4,p_5.jpg,colder,hotter,"[fuller, curvier]",drinks,
...,...,...,...,...,...,...
252,k_60.jpg,fatter,skinnier,"[narrower, fancier, taller]",people,
253,k_61.jpg,nearer,farther,"[heavier, bluer, smoother]",objects,
254,k_62.jpg,shinier,duller,"[heavier, curvier, curlier]",piggybank,santa
255,k_63.jpg,fatter,skinnier,"[drier, broader, blacker]",fishes,
256,k_64.jpg,nearer,farther,"[heavier, fresher, higher]",salmon filets,

In [44]:
all_labels_aug.to_pickle('all_labels')